services:
  db:
    image: postgres:17
    container_name: social_media_store
    environment:
      POSTGRES_USER: social_media_store_user
      POSTGRES_PASSWORD: social_media_store_pass
      POSTGRES_DB: social_media_store
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5434:5432"

volumes:
  postgres_data: