name: 🚀 Deploy to server on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload & Run Remote Commands
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Install deps & build
        run: |
          npm ci
          npm run build

      - name: 📤 Upload build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2022
          source: "dist/**"
          strip_components: 1
          target: "social-media-store/backend"
          overwrite: true
          rm: true

      - name: 🧠 Run post-deploy commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2022
          script: |
            cd social-media-store/backend
            npm install --omit=dev
            pm2 describe social-media-store > /dev/null \
              && pm2 restart social-media-store \
              || pm2 start index.js --name social-media-store
            pm2 save
            npm run migrate
